project:
  type: book
  output-dir: docs

book:
  title: "<b>Introduction to Computing</b><br>CSCI 0145"
  chapters:
   - text: Welcome!
     href: index.qmd 
   - syllabus.qmd
   - schedule.qmd
   - acknowledgements.qmd
  favicon: assets/img/icons/favicon.png


format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    number-depth: 0